version: "3.0"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - db:db
  php:
    build: php
    expose:
      - "9000"
    volumes:
      - ./php/www:/var/www/html
  apache2:
    image: webdevops/apache:latest
    args:
      - PHP_SOCKET=php:9000
    volumes:
      - ./php/www:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    