version: "3.0"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - db:db
  apache2:
    image: httpd
    links:
      - php
    ports:
      - "8081:80"
  php:
    image: php
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html
    